name: Publish Docker Image to GHCR

on:
  push:
    branches: [ "main" ]
    paths:
      - 'Dockerfile'
      - 'Cargo.toml'
      - 'Cargo.lock'
      - 'src/**'
  release:
    types: [created, published]
  workflow_dispatch:

permissions: read-all

jobs:
  build-and-push:
    name: Build & Push Multi-Arch Container
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up QEMU (multi-architecture emulation)
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3.6.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Razor
        id: meta-razor
        uses: docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804 # v5.7.0
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/razor
            ghcr.io/${{ github.repository_owner }}/tokenectomy
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=ref,event=branch
            type=ref,event=tag
            type=semver,pattern={{version}}

      - name: Build and Push Multi-Arch Images
        uses: docker/build-push-action@ca052bb54ab0790a636c9b5f226502c73d547a25 # v5.4.0
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta-razor.outputs.tags }}
          labels: ${{ steps.meta-razor.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
